### ISSUE TITLE
auto-disable on fatal error (don't error on every buffer)

### ISSUE THREAD

**Issue by teto** [neovim/nvim-lspconfig#106]
When nvim-lsp doesnt find the executable specified in the nvim-lsp config, it spits out a message.
`Error executing lua ...9kqpskva35-neovim/share/nvim/runtime/lua/vim/lsp/rpc.lua:212: The given command "ghcide" is not executable.`
If you change the current buffer, the autocmd triggers and the same error appears again and again.
coc.nvim only fails on the first bufffer.

This may be considered as a fault relying on the user environment so maybe we don't need to fix it but due to my setup (almost no program globally installed, all in virtual env), it happens quite often.

**Comment by justinmk** [comment]
Handler should maybe just remove itself (and mention this in the message). Else we are running the same failing check, even if the error would hidden. Example:

    lsp: "ghcide" not found; handler disabled

But then users might have some autocmds invoking the thing. Should perhaps also store a `last_result` field in some object, which the handler checks.

**Comment by teto** [comment]
cool. I will try to come up with something.

**Comment by williamboman** [comment]
Hey @mjlbach 👋! I'm running into an interesting predicament here with https://github.com/williamboman/nvim-lsp-installer due to this check.

Currently this plugin will override the provided `cmd`, so that it actually uses the executable that was installed locally by the plugin. However, I'm exploring whether just prepending the `PATH` with the path to the installed executable and providing it in `cmd_env` (while leaving `cmd` untouched) would work in a reliable manner. This is where I started running into this unexpected error, where it uses the neovim instance searchpath to locate the executable (which more or less means global installations are assumed). I'm wondering if we could defer this check until the cmd is actually spawned? I'd be more than happy to contribute with a PR once we agree on a way forward!
