### ISSUE TITLE
preview window instead of hover for persistent function declaration

### ISSUE THREAD

**Issue by ryanbrate** [neovim/nvim-lspconfig#1165]
Hi,

Is there any way to replace i) hover's floating window with the built-in nvim preview window and ii) make the function declaration preview supplied by hover, whether floating or not, persistently visible as I type?

I've searched the documentation, git Issues etc - but have found no answers.

many thanks, 

Ryan

**Comment by mjlbach** [comment]
None of the features you are asking about are implemented in this repo. This just provides configuration for launching language servers for the built-in client in neovim. If you *did* want to ask about overriding the built-in client's UX stuff, you'd want to ask on our [discourse](https://neovim.discourse.group/c/7-category/7).

To directly answer your question, there is no built-in option about for it.  1.You'd have to override the hover handler to use preview instead of floating window, and 2. I think what you are asking for is https://github.com/ray-x/lsp_signature.nvim (hover shows definition, not the declaration).
