### ISSUE TITLE
case sensitivity causes multiple servers running in the same directory

### ISSUE THREAD

**Issue by Rodrigodd** [neovim/nvim-lspconfig#1168]
I am having a bug where two servers are started for the same workspace. After debugging, i discovery that a diference in the case of the path of the file cause the bug. This is my `:messages` output after adding a `nvim_err_writeln` in [this line](https://github.com/neovim/nvim-lspconfig/blob/5b0fa84ee35006e06142f98b8a5b28d79cfa5000/lua/lspconfig/util.lua#L226).

![image](https://user-images.githubusercontent.com/51273772/130370627-7cc05ed5-3e5e-4cef-9f27-ed05e007a9c0.png)

As you can see, for some reason, there is a difference in the case of the drive D:\\, which cause the bug. I don't investigate further to know why this happen. Running `:buffers` show that the path of the file that has this difference:
```
:buffers
  1  h   "src\style.rs"                 linha 1
  3  h   "src\text.rs"                  linha 1
  6  a   "examples\main.rs"             linha 1
 10  h   "d:\repos\rust\crui\src\graphics.rs" linha 1
 11  h   "src\render.rs"                linha 1
```

Maybe the `root_dir` should be normalized?

- `nvim --version`: NVIM v0.6.0-dev+166-g8331cd13c
- nvim-lspconfig version(commit hash): 5b0fa84
- What language server (If the problem is related to a specific language server): rust-analyzer
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? Not checked.
- Operating system/version: Windows 10.0.19042

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: rust_analyzer: configuration checked.
</details>

**Comment by aqez** [comment]
Just wanted to add some extra info here as I'm investigating - it appears that calling `api.nvim_buf_get_name(bufnr)` from `configs.lua` is giving back the lower cased name. However, when I run `:lua print(vim.api.nvim_buf_get_name(..))`, it gives back the correct casing. This line here:

https://github.com/neovim/nvim-lspconfig/blob/756549de506bcf9cf9361e87c8b360154b9d7235/lua/lspconfig/configs.lua#L180

**Comment by aqez** [comment]
I believe I've made some headway on this. So this is what is happening, at least on my machine - when I open a file from neovim directly using `:e somefile` or using NERDTree or similar, I get the path I would expect to see on windows. This is usually a relative path from the current directory, so listing buffers that I've opened this way I'll usually see something like `src\main.rs` or `some\other\place\file.cs`. 

However, when opening a file from a language server response, we get back a uri, which is usually in the form of `file:///c:/full/path/to/somewhere/file.rs`. This then gets passed back to neovim, which gives it to `location_handler`(https://github.com/neovim/neovim/blob/c9e5c778b0aa3e8af9dee2ebde199285056fc20c/runtime/lua/vim/lsp/handlers.lua#L273) and it opens it directly like that, by calling `vim.uri_to_bufnr(uri)`(https://github.com/neovim/neovim/blob/68b2a9e5693592d98d8a3e84bcad288704f66bb1/runtime/lua/vim/uri.lua#L124), which subsequently calls `uri_to_fname`, defined just above (https://github.com/neovim/neovim/blob/68b2a9e5693592d98d8a3e84bcad288704f66bb1/runtime/lua/vim/uri.lua#L104), and this just strips off the `file:///` portion. So really it's because we get back a lower case name from the language server.

**Comment by petrosAth** [comment]
I run through the same bug under Windows. It makes lsp return diagnostics twice (once per server).
The fix you are trying to push works, but the line
`root_dir = M.path.normalize_path(root_dir)`
has to be moved above the single_file_mode check that got added after your PR.

**Comment by mjlbach** [comment]
I filed an upstream issue, I'd rather address this in core (we can merge a workaround in lspconfig), I think we should only sanitize for internal lspconfig tracking though, not when sending to the language server.

https://github.com/neovim/neovim/issues/16331
