### ISSUE TITLE
Show source in diagnostics

### ISSUE THREAD

**Issue by ranebrown** [neovim/nvim-lspconfig#1230]
What is the correct way to show the LSP source in the diagnostics as outlined [here](https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#show-source-in-diagnostics). With the recent changes to the function signature in https://github.com/neovim/neovim/pull/15504 I was having trouble getting things working and wasn't sure if `vim.lsp.with` should now be used somehow as well. Thanks in advance for any help!

**Comment by gegoune** [comment]
https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#show-source-in-diagnostics

**Comment by mjlbach** [comment]
I updated the wiki

**Comment by ranebrown** [comment]
Thanks! That works but the new display is only shown for virtual text not popup. Is there a different `vim.lsp.diagnostic.display` call that applies to popup text?

**Comment by mjlbach** [comment]
No, that actually doesn't involve a handler. You'll need to write your own function like show_line_diagnostics 
https://github.com/mjlbach/neovim/blob/997a9c879215bc01a928de3e762955878314ec6a/runtime/lua/vim/lsp/diagnostic.lua#L1132-L1173 that gets the diagnostics per client_id and prepends.

The issue, is the previous implementation in the wiki modified the diagnostic cache which would break code actions (which send the diagnostics as part of the context to the language server). We had complaints about this, so I modified the snippet, which since it no longer modifies the diagnostic cache will not be implicitly picked up with show_line_diagnostics.
