### ISSUE TITLE
E5113: Error while calling lua chunk configs.lua:10: attempt to index

### ISSUE THREAD

**Issue by DanimanX** [neovim/nvim-lspconfig#1531]
### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile

### Nvim-lspconfig version

80e101e7ec12835737f35452f07a94d9cc2e690d

### Operating system and version

5.15.5-zen1-1-zen

### Affected language servers

all

### Steps to reproduce

1.- :PackerUpdate
2.- nvim

### Actual behavior

When i upgrade to the last commit in master, i've this error:
E5113: Error while calling lua chunk: ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil v
alue)
stack traceback:
        ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: in function '__newindex'
        ...ack/packer/start/nvim-lspinstall/lua/lspinstall/util.lua:15: in function 'extract_config'
        ...start/nvim-lspinstall/lua/lspinstall/servers/angular.lua:1: in main chunk
        [C]: in function 'require'
        .../packer/start/nvim-lspinstall/lua/lspinstall/servers.lua:2: in main chunk
        [C]: in function 'require'
        ...ite/pack/packer/start/nvim-lspinstall/lua/lspinstall.lua:1: in main chunk
        [C]: in function 'require'
        /home/danimanx/.config/nvim/lua/lspinstall/lspinstall.lua:1: in main chunk
        [C]: in function 'require'
        /home/danimanx/.config/nvim/init.lua:10: in main chunk

### Expected behavior

not get the error

### Minimal config

```Lua
-/-

Can't get this to work with the "minimal_init".
```

### Health check

Running healthchecks...
Error detected while processing function health#check:
line   37:
E684: list index out of range: 0

### LSP log
https://gist.github.com/DanimanX/3c50523513d6c198d705a57aeed03e7c

**Comment by mjlbach** [comment]
Lspinstall is unsupported and archived
________________________________
From: DanimanX ***@***.***>
Sent: Thursday, December 2, 2021 4:53:20 PM
To: neovim/nvim-lspconfig ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neovim/nvim-lspconfig] E5113: Error while calling lua chunk configs.lua:10: attempt to index (Issue #1531)


Description

When i upgrade to the last commit in master, i've this error:
E5113: Error while calling lua chunk: ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil v
alue)
stack traceback:
...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: in function '__newindex'
...ack/packer/start/nvim-lspinstall/lua/lspinstall/util.lua:15: in function 'extract_config'
...start/nvim-lspinstall/lua/lspinstall/servers/angular.lua:1: in main chunk
[C]: in function 'require'
.../packer/start/nvim-lspinstall/lua/lspinstall/servers.lua:2: in main chunk
[C]: in function 'require'
...ite/pack/packer/start/nvim-lspinstall/lua/lspinstall.lua:1: in main chunk
[C]: in function 'require'
/home/danimanx/.config/nvim/lua/lspinstall/lspinstall.lua:1: in main chunk
[C]: in function 'require'
/home/danimanx/.config/nvim/init.lua:10: in main chunk

Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile

Nvim-lspconfig version

80e101e<https://github.com/neovim/nvim-lspconfig/commit/80e101e7ec12835737f35452f07a94d9cc2e690d>

Operating system and version

5.15.5-zen1-1-zen

Affected language servers

all

Steps to reproduce

1.- :PackerUpdate
2.- nvim

Actual behavior

When i upgrade to the last commit in master, i've this error:
E5113: Error while calling lua chunk: ...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil v
alue)
stack traceback:
...ck/packer/start/nvim-lspconfig/lua/lspconfig/configs.lua:10: in function '__newindex'
...ack/packer/start/nvim-lspinstall/lua/lspinstall/util.lua:15: in function 'extract_config'
...start/nvim-lspinstall/lua/lspinstall/servers/angular.lua:1: in main chunk
[C]: in function 'require'
.../packer/start/nvim-lspinstall/lua/lspinstall/servers.lua:2: in main chunk
[C]: in function 'require'
...ite/pack/packer/start/nvim-lspinstall/lua/lspinstall.lua:1: in main chunk
[C]: in function 'require'
/home/danimanx/.config/nvim/lua/lspinstall/lspinstall.lua:1: in main chunk
[C]: in function 'require'
/home/danimanx/.config/nvim/init.lua:10: in main chunk

Expected behavior

not get the error

Minimal config

-/-

Can't get this to work with the "minimal_init".

Health check

Running healthchecks...
Error detected while processing function health#check:
line 37:
E684: list index out of range: 0

LSP log

https://gist.github.com/DanimanX/3c50523513d6c198d705a57aeed03e7c.js
