### ISSUE TITLE
jdtls Provides a Start Up Script

### ISSUE THREAD

**Issue by schrieveslaach** [neovim/nvim-lspconfig#1819]
### Language server

jdtls

### Requested feature

Since version 1.9.0 of eclipse.jdt.ls there is a [wrapper script](https://github.com/eclipse/eclipse.jdt.ls/pull/2005) that handles all the start-up configuration of the JVM. So [this code](https://github.com/neovim/nvim-lspconfig/blob/700eda91316a876757bf306fd709fde75aadb36a/lua/lspconfig/server_configurations/jdtls.lua#L97-L111) could be simplified.

There are also some package managers that install the script as a executable, for example:

- Arch Linux: https://aur.archlinux.org/packages/jdtls
- Homebrew: https://formulae.brew.sh/formula/jdtls (https://github.com/Homebrew/homebrew-core/pull/96232)

**Comment by agorgl** [comment]
Current nvim-lspconfig jdtls server configuration also does not work by default, checking the lsp.log shows various `java.nio.file.AccessDeniedException` exceptions. Running the cmd shown in LspInfo by hand, I can see clearly:
```
The configuration area at '/usr/share/java/jdtls/config_linux' is not writable.  Please choose a writable location using the '-configuration' command line option.
```
Tested on Arch Linux with latest jdtls AUR package.

Using the provided wrapper script will solve these kind of problems, because instead of passing the original jdtls config_<linux|win|mac> folder in -configuration option, it will make a copy first to a user provided location:

https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script

**Comment by agorgl** [comment]
Prepping a PR for this.

**Comment by schrieveslaach** [comment]
@agorgl, thanks for stepping in.

**Comment by agorgl** [comment]
#1833 is now merged on master, this can be closed
