### ISSUE TITLE
'No information available' wrongfully triggers when hovering tailwindcss class

### ISSUE THREAD

**Issue by zakissimo** [neovim/nvim-lspconfig#1931]
### Description

Running `:lua vim.lsp.buf.hover()` on a tailwindcss class opens a floating window with the intended information. But notifies wrongfully 'No information available'.

![image](https://user-images.githubusercontent.com/64891486/170885899-35312ecc-7b53-4ec3-8780-acfb5d366ac0.png)

### Neovim version

NVIM v0.8.0-dev+313-g7b952793d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

latest

### Operating system and version

Linux dell 5.18.0-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 May 2022 22:00:36 +0000 x86_64 GNU/Linux

### Affected language servers

tailwindcss

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by mmirus** [comment]
Commenting here to help anyone else who may dig into this scenario.

At least for me, this is caused by having multiple language servers active for the same file. So, for example, when editing a typescriptreact file, I have tsserver, the Tailwind language server, and others active.

In this scenario, if I hover a symbol that only one of the language servers supports, the other servers respond with "No information available".

This isn't particularly annoying when it just goes to the default messages area, but when you're using something like nvim-notify it's much worse, as the messages are far more visible.

Fortunately, it's easy to add filtering once you know what's going on. Credit here for the solution: https://github.com/rcarriga/nvim-notify/issues/114#issuecomment-1179754969

```lua
local banned_messages = { "No information available" }
vim.notify = function(msg, ...)
  for _, banned in ipairs(banned_messages) do
    if msg == banned then
      return
    end
  end
  require("notify")(msg, ...)
end

```

It might be a nice upstream (neovim core, not here in lspconfig) enhancement to only send this message when none of the attached language servers come back with anything, but there may be good technical reasons for avoiding that. :man_shrugging: Waaaay past my knowledge level.

**Comment by gtnbssn** [comment]
Been suffering from this as well, this looks like it could fix it: https://github.com/neovim/neovim/issues/20457#issuecomment-1266782345

**Comment by mmirus** [comment]
Note that I updated [the above snippet](https://github.com/neovim/nvim-lspconfig/issues/1931#issuecomment-1297599534) to return the result of `require("notify")(msg, ...)`.

This is used by some plugins, for example to update an existing notification as a process runs rather than spawning multiple notifications.

Example of the kind of problem not returning that can cause: https://github.com/dmmulroy/tsc.nvim/issues/2

**Comment by Armadillidiid** [comment]
> Commenting here to help anyone else who may dig into this scenario.
> 
> At least for me, this is caused by having multiple language servers active for the same file. So, for example, when editing a typescriptreact file, I have tsserver, the Tailwind language server, and others active.
> 
> In this scenario, if I hover a symbol that only one of the language servers supports, the other servers respond with "No information available".
> 
> This isn't particularly annoying when it just goes to the default messages area, but when you're using something like nvim-notify it's much worse, as the messages are far more visible.
> 
> Fortunately, it's easy to add filtering once you know what's going on. Credit here for the solution: [rcarriga/nvim-notify#114 (comment)](https://github.com/rcarriga/nvim-notify/issues/114#issuecomment-1179754969)
> 
> ```lua
> local banned_messages = { "No information available" }
> vim.notify = function(msg, ...)
>   for _, banned in ipairs(banned_messages) do
>     if msg == banned then
>       return
>     end
>   end
>   return require("notify")(msg, ...)
> end
> ```
> 
> It might be a nice upstream (neovim core, not here in lspconfig) enhancement to only send this message when none of the attached language servers come back with anything, but there may be good technical reasons for avoiding that. man_shrugging Waaaay past my knowledge level.

Where do I add this if I am using LazyVim?

**Comment by mmirus** [comment]
@Armadillidiid Since LazyVim comes with nvim-notify, you'll want to look in the LazyVim docs for how to override or extend the spec for that plugin, and add the snippet into the `config` function. I only use lazy.nvim, not LazyVim, so I just have `lua/plugins/notify.lua` with the following:

```lua
return {
  "rcarriga/nvim-notify",
  config = function()
    -- See https://github.com/neovim/nvim-lspconfig/issues/1931#issuecomment-1297599534
    -- An alternative solution: https://github.com/neovim/neovim/issues/20457#issuecomment-1266782345
    local banned_messages = { "No information available" }
    vim.notify = function(msg, ...)
      for _, banned in ipairs(banned_messages) do
        if msg == banned then
          return
        end
      end
      return require("notify")(msg, ...)
    end
  end,
}

```

**Comment by gtnbssn** [comment]
For lazyvim, an answer was given in a discussion there : https://github.com/LazyVim/LazyVim/discussions/830

**Comment by birdmanmandbir** [comment]
For lazyvim, just use this:
https://github.com/LazyVim/LazyVim/discussions/830#discussioncomment-7757328

**Comment by patelharsh9797** [comment]
Can i add filter for this?
![Screenshot from 2024-02-08 21-26-25](https://github.com/neovim/nvim-lspconfig/assets/105432105/75777f6f-75dc-4e88-bbbd-bc2f431b7b67)

**Comment by bentruyman** [comment]
If you're using [folke/noice.nvim](https://github.com/folke/noice.nvim), add this to your config:

```lua
opts = {
  routes = {
    {
      filter = {
        event = "notify",
        find = "No information available",
      },
      opts = {
        skip = true,
      },
    },
  },
}
```
