### ISSUE TITLE
Error executing Lua callback: ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:18: bad argument #1 to 'pairs' (table expected, got function)

### ISSUE THREAD

**Issue by lessthanseventy** [neovim/nvim-lspconfig#2134]
### Description

stack traceback:
        [C]: in function 'pairs'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:18: in function 'trim_blankspace'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:31: in function 'remove_newlines'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:107: in function 'make_client_info'
        ...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:194: in function <...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:147>
        ...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:64: in function <...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:63>

### Neovim version

IM v0.8.0-dev-1081-g907fc8ac3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

12735ee94a3eca96c4ebb799a62a0a7aa4733107

### Operating system and version

Ubuntu 20.04

### Affected language servers

all

### Steps to reproduce

run :LspInfo

### Actual behavior

Error shown above, blank floating window comes up

### Minimal config

```Lua
N/A
```

### LSP log

https://gist.github.com/lessthanseventy/618c2d2d060a86f8c2dd3bed48c1dfc7

**Comment by glepnir** [comment]
I can't reproduce .you should check it with min config

**Comment by agretta** [comment]
I suspect that this is due to a recent update to null-ls [here](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1073), specifically [this](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1073/files#diff-e9959f74363ea07a0680c84ef05a94ca988b69b7ce2df7367dd8ccf4dba50828L88-R92) diff

I am experiencing the same error when running `:LspInfo`, and if I checkout null-ls to a previous commit before the change listed above (`cdef04dfad2d1a6d76f596ac63600e7430baaabe` for example) the error stops appearing.

some dumb debugging, if I tweak make_client_info [here](https://github.com/neovim/nvim-lspconfig/blob/12735ee94a3eca96c4ebb799a62a0a7aa4733107/lua/lspconfig/ui/lspinfo.lua#L104-L105), ...
```
local function make_client_info(client)
  local client_info = {}

  vim.pretty_print(client.config.name)
  vim.pretty_print(client.config.cmd)
  client_info.cmd = remove_newlines(client.config.cmd)  
```

calling `:LspInfo` prints out this with the the most recent null-ls
```  
"sumneko_lua"
{ "lua-language-server" }
"null-ls"
<function 1>
```
and this with the working null-ls commit
```  
"sumneko_lua"
{ "lua-language-server" }
"null-ls"
{ "nvim" }
```

**Comment by glepnir** [comment]
not lspconfig issue .

**Comment by rodhash** [comment]
> I suspect that this is due to a recent update to null-ls [here](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1073), specifically [this](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/1073/files#diff-e9959f74363ea07a0680c84ef05a94ca988b69b7ce2df7367dd8ccf4dba50828L88-R92) diff
> 
> I am experiencing the same error when running `:LspInfo`, and if I checkout null-ls to a previous commit before the change listed above (`cdef04dfad2d1a6d76f596ac63600e7430baaabe` for example) the error stops appearing.
> 
> some dumb debugging, if I tweak make_client_info [here](https://github.com/neovim/nvim-lspconfig/blob/12735ee94a3eca96c4ebb799a62a0a7aa4733107/lua/lspconfig/ui/lspinfo.lua#L104-L105), ...
> 
> ```
> local function make_client_info(client)
>   local client_info = {}
> 
>   vim.pretty_print(client.config.name)
>   vim.pretty_print(client.config.cmd)
>   client_info.cmd = remove_newlines(client.config.cmd)  
> ```
> 
> calling `:LspInfo` prints out this with the the most recent null-ls
> 
> ```
> "sumneko_lua"
> { "lua-language-server" }
> "null-ls"
> <function 1>
> ```
> 
> and this with the working null-ls commit
> 
> ```
> "sumneko_lua"
> { "lua-language-server" }
> "null-ls"
> { "nvim" }
> ```

Same here.. checking out `cdef04df` stops the error
