### ISSUE TITLE
Resourcing $MYVIMRC breaks nvim-lsp

### ISSUE THREAD

**Issue by nhooyr** [neovim/nvim-lspconfig#272]
- `nvim --version`: `v0.5.0-60c581b`
- nvim-lsp version(commit hash): `94cce7448f34f172492d98ff6efe10986f73eb9e`
- `:checkhealth` result: Everything passes
- Operating system/version: macOS 10.15.5
- Terminal name/version: Terminal.app
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

If I source my $MYVIMRC again lsp stops working. i.e omnifunc doesn't nothing and no diagnostics pop up.

```viml
  if !exists("g:nhooyr_lsp")
    "let g:nhooyr_lsp = 1
    lua << EOF
    local lsp_loaded, lsp = pcall(require, 'nvim_lsp')
    if not lsp_loaded then
      return
    end

    lsp.gopls.setup{}
    lsp.tsserver.setup{}
    lsp.vimls.setup{}
    lsp.clangd.setup{}
EOF
  endif
```

So I added an if guard around it to load only once.

**Comment by justinmk** [comment]
i think the main takeaway here is we need better logging/inspection tooling. though narrowing the particular problem here would be good meanwhile

**Comment by mjlbach** [comment]
@nhooyr I don't know if this is really a bug.

1. Use [this](https://gist.github.com/mjlbach/70bb5a2924754f25608e9a00e8d0723f) minimal_init.lua
2. Install pyright `npm i -g pyright` and open a python file in a git repo with `nvim -u ~/.config/nvim/miminal_init.lua`
3. See diagnostics
4. Trigger reload with `<space>rc`
5. No diagnostics
6. Trigger attaching of the buffer with e!
7. Diagnostics appear

I think your issue is with step 6, but what would the alternative be? 

1. We could forcibly restart/reattach language servers to all buffers, but that may not be desirable (as it deviates from the current behavior)
2. We could keep all language servers alive with the old settings, but then users might get frustrated because they *wanted* their settings to change.

**Comment by nhooyr** [comment]
> We could forcibly restart/reattach language servers to all buffers, but that may not be desirable (as it deviates from the current behavior), and may introduce high cpu load when a user wants neovim to reflect the state it would be at start (with no language servers attached).

Doesn't have to be automatic on all buffers, only what's visible. After sourcing `$MYVIMRC`, any visible buffer should have the language server reattach.

If I wanted neovim to reflect the state it would be with no language servers attached, I'd close all buffers or restart it.

**Comment by mjlbach** [comment]
Just to be clear, you want the servers to shutdown and restart, with only the currently open buffer spawning/attaching to a language server, rather than the previously active language servers to remain active.
