### ISSUE TITLE
Getting "undefined global `vim`" warnings with neovim/nvim-lspconfig enabled

### ISSUE THREAD

**Issue by sdondley** [neovim/nvim-lspconfig#2743]
### Description

I'm getting warning with neovim/nvim-lspconfig enabled. When disabled, warning no longer appear.

![image](https://github.com/neovim/nvim-lspconfig/assets/2506364/4376de6f-bf09-430b-a244-d8844987a14a)

### Neovim version

NVIM v0.9.0
Build type: MinSizeRel
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

b609127

### Operating system and version

alpine:latest

### Affected language servers

all?

### Steps to reproduce

1) add in keymap in lua
2) enable this module
3) see warnings in file

### Actual behavior

<img width="1946" alt="image" src="https://github.com/neovim/nvim-lspconfig/assets/2506364/222b5f33-75f0-48ca-9dc2-6e20a86f48d3">

### Expected behavior

No warnings

### Minimal config

```Lua
I don't know what this is trying to tell me to do.
```

### LSP log

don't know how to do this.

**Comment by justinmk** [comment]
The warning you are seeing is your Lua LSP server doing its job: it is warning you about stuff.

nvim-lspconfig is just a collection of configs. When you remove it, your Lua LSP server happens to stop working, so the warning goes away.

The actual problem is that Lua LSP doesn't know that `vim` is a global that Nvim always defines. To tell Lua LSP about that you would need something like: 

https://github.com/neovim/neovim/blob/996dd36c77321ea91758b5996d152a2f37af99dd/contrib/luarc.json#L5-L7

**Comment by sdondley** [comment]
OK, thanks. For other newbs out there with the same problem using lazy.nvim, this is what fixed it for me, added to my lua/plugins directory:

```
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        lua_ls = {
          settings = {
            Lua = {
              diagnostics = {
                globals = { "vim" },
              },
            },
          },
        },
      },
    },
  },
```
