### ISSUE TITLE
completion not working with LanguageServer.jl

### ISSUE THREAD

**Issue by yuntan** [neovim/nvim-lspconfig#279]
Linter is working but \<C-X\>\<C-O\> completion not working.

```vim
lua << EOF
local nvim_lsp = require 'nvim_lsp'
nvim_lsp.julials.setup {}
EOF

autocmd MyAutoCmd Filetype julia setl omnifunc=v:lua.vim.lsp.omnifunc
```

`setl omnifunc?` shows `omnifunc=v:lua.vim.lsp.omnifunc`

lsp.log:
```
[ ERROR ] 2020-06-15T07:56:22+0900 ] ...nt_nvimJSMGq3/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"julia"	"stderr"	'┌ Info: Running language server\n│   env = "/home/tokuyuuto/.cache/nvim/nvim_lsp/julials/Project.toml"\n│   pwd() = "/home/tokuyuuto/atcoder.jl"\n│   project_path = "/home/tokuyuuto/.julia/environments/v1.4"\n└   depot_path = ""\n'
[ ERROR ] 2020-06-15T07:56:44+0900 ] ...nt_nvimJSMGq3/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"julia"	"stderr"	"[ Info: Indexing DataStructures...\n"
[ ERROR ] 2020-06-15T07:57:22+0900 ] ...nt_nvimJSMGq3/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"julia"	"stderr"	"[ Info: Received new data from Julia Symbol Server.\n"
```

- LanguageServer.jl: v3.1.0
- `nvim --version`: NVIM v0.5.0-559-ga0a84fc9e
- nvim-lsp version(commit hash): 31859d4
- `:checkhealth` result
  INFO: julials: configuration checked.
- What language server(If the problem is related to a specific language server): LanguageServer.jl (julia)
- Operating system/version: Debian buster
- Terminal name/version: crosh (Chrome OS)
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup
- open julia source
- wait for 30 seconds
- enter some text (example `on` for `ones`)
- \<C-X\>\<C-O\>
- message `Pattern not found`

**Comment by h-michael** [comment]
@kdheepak 
Do you know what happened?

**Comment by tjdevries** [comment]
Do you have the omni func set to the LSP source? It doesn't look like it in your minimal init.vim

**Comment by kdheepak** [comment]
Yes, you have to set omnifunc. I am on my phone right now, and my internet isn't cooperating with me so I can't look into this more at the moment. The people that commented above are the neovim experts :)

This is a non answer but I wanted to add my experience. In the past I have had mixed results using the built in omnifunc set to the LSP source. Even using https://github.com/haorenW1025/completion-nvim didn't work for me with julia. _I think_ it is because LanguageServer.jl always returns only snippets. See https://github.com/julia-vscode/LanguageServer.jl/issues/747. I haven't looked into it enough and haven't dug through the source to check if this is the reason (although I have been meaning to figure out what is going on). 

Though, I have been using deoplete and deoplete-lsp and I know that works, and _I think_ it is because it doesn't distinguish between snippets and plain text completion. This means snippet completion with deoplete doesn't work well but there's an issue for that: https://github.com/Shougo/deoplete-lsp/issues/7.

**Comment by yuntan** [comment]
I'd set omnifunc (from before creating the issue).

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
