### ISSUE TITLE
ElixirLS completion inserts function parameters

### ISSUE THREAD

**Issue by to-str** [neovim/nvim-lspconfig#295]
Hi

I set up nvim-lsp yesterday and noticed this behaviour:
<img width="1152" alt="Screenshot 2020-07-03 at 09 07 53" src="https://user-images.githubusercontent.com/231959/86441688-1ea2fd00-bcfc-11ea-8817-4a25fa7f8a33.png">

As you can see in the screenshot if I autocomplete a function from elirix-ls it inserts the full function header basically. This happens with deoplete as well as with just `set omnifunc=v:lua.vim.lsp.omnifunc`. I would assume that nvim misunderstands the LSP output or something along those lines? Because the information is correct, it just inserts too much of it.

This happens with both, the `:LspInstall elixir-ls` server and the one I installed myself.

I did not see this behaviour with vim-ale using the same language server, nor with vim-lsp.

**Comment by t0str** [comment]
I want to add a correction. If I use the language server that `:LspInstall` provides it actually behaves slightly differently. Instead of completing the function header with all parameters, it completes `GenServer.start_link/3`, which seems to be the same kind or error in general, but at least it's much quicker to backspace over ;)

**Comment by mjlbach** [comment]
Is this still an issue? I'm not able to reproduce with the latest elixir-ls

**Comment by to-str** [comment]
Installed nvim-lsp & friends again on my setup, with neovim@HEAD, elixir-ls@HEAD everything works as expected. Thanks for bringing it to my attention again, had forgotten about the ticket!
