### ISSUE TITLE
Lsp shows not installed but is actually installed

### ISSUE THREAD

**Issue by HyperAfnan** [neovim/nvim-lspconfig#3185]
### Description

Hey I've been trying to configure language servers for my web development but I'm have an issue while setting it up 
I've installed the language servers but it's showing that it isn't installed 
![Screenshot_20240531_110229_Termux](https://github.com/neovim/nvim-lspconfig/assets/98379782/77a52960-16a2-4b75-810b-ee35210aa162)
![Screenshot_20240531_110109_Termux](https://github.com/neovim/nvim-lspconfig/assets/98379782/25c88c75-27c2-4f9c-92c5-6e5a51304560)

**Comment by HyperAfnan** [comment]
![Screenshot_20240531_110828_Termux](https://github.com/neovim/nvim-lspconfig/assets/98379782/e2c4dc85-5fc1-4fcb-9fdf-4a5eed3fe994)
This is the screenshot of LspInfo

**Comment by seanbreckenridge** [comment]
What do you see in `:LspLog`? Also, this is just a hunch since you're on termux, but if you edit `emmet-language-server`, does it have a shebang at the top like `#!/usr/bin/env node`?

I don't know the reason why, but I've had issues with termux resolving those.

If you change it to a full path to node on termux like `#!/data/data/com.termux/files/usr/bin/node`, thats fixed the issue I've had with `bash-language-server` in the past, so might work here as well.

**Comment by HyperAfnan** [comment]
Yeah it's now working 
Thanks for the help man
