### ISSUE TITLE
Provide API to exclude buffers

### ISSUE THREAD

**Issue by heroin-moose** [neovim/nvim-lspconfig#3250]
### Description

I cannot find a way to prevent a client attaching to a buffer. It's especially PITA with clangd, because C does not have a unified build system. It would be nice to have a way to check for prerequisites and decide whether I want to allow the client to attach or not.

**Comment by glepnir** [comment]
stop client in filetype event callback.

**Comment by heroin-moose** [comment]
Can you give an example?

**Comment by glepnir** [comment]
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'c',
  callback = function(args)
    local bufname = vim.api.nvim_buf_get_name(args.buf)
    if bufname:match('some regex') then
      vim.schedule(function()
        local client = vim.lsp.get_clients({ bufnr = args.buf })[1]
        if client then
          vim.lsp.buf_detach_client(args.buf, client.id)
        end
      end)
    end
  end,
})
```

**Comment by heroin-moose** [comment]
Actually, a simpler solution:

```
lspconfig.clangd.setup({
  root_dir = function(fname)
    return lspconfig.util.root_pattern({'compile_commands.json'})(fname)
  end,
  single_file_support = false
})
```
Setting `root_dir` required because by default clangd search for everything related to C/C++ stack, including .git.

**Comment by FelipeLema** [comment]
none of the proposed solutions work on manually-started servers attaching due to matching filetype:

say I want to run `ruff_lsp` only on buffers that end in `.py`
- open a python script `my-script` (`ruff_lsp` not started 😄 )
- open a python source file `some_module.py` (triggers `require('lspconfig.configs').ruff_lsp.launch()`, `ruff_lsp` attaches to `my-script` because it's the same `filetype` 😢 )
