### ISSUE TITLE
texlab root not being detected correctly

### ISSUE THREAD

**Issue by a-torgovitsky** [neovim/nvim-lspconfig#3262]
### Description

Directory structure is this:

```console
tree ./texlab-root-mwe  -a --dirsfirst -L 2                                                        ─╯
./texlab-root-mwe
├── ch1
│   ├── ch1.aux
│   ├── ch1.fdb_latexmk
│   ├── ch1.fls
│   ├── ch1.log
│   ├── ch1.pdf
│   ├── ch1.synctex.gz
│   ├── ch1.tex
│   ├── .texlabroot
│   └── texlabroot
├── .git
│   ├── branches
│   ├── hooks
│   ├── info
│   ├── objects
│   ├── refs
│   ├── config
│   ├── description
│   └── HEAD
├── main.aux
├── main.fdb_latexmk
├── main.fls
├── main.log
├── main.pdf
├── main.synctex.gz
└── main.tex

7 directories, 19 files
```

If I open `ch1.tex` then `:LspInfo` shows that the root directory is the top level `./texlab-root-mwe`. My understanding is that the presence of either `.texlabroot` or `texlabroot` (I have both) should force the root directory to be detected as `./texlab-root-mwe/ch1`.
This issue [was discussed](https://github.com/latex-lsp/texlab/issues/1061) in `texlab`, but the conclusion was that it was the domain of `nvim-lspconfig`.
#3005  seems aimed at addressing the same issue, but doesn't seem to have worked?

**Comment by DimitrisDimitropoulos** [comment]
This is expected behavior `util.root_pattern`, gives priority to the first item on the list, [see](https://github.com/neovim/nvim-lspconfig/commit/021906284dcfb938bc236f8295af2650c60cb807). If you want to change the default it is pretty easy to do on your own, for example something along the lines:
```lua
  require('lspconfig').texlab.setup {
    root_dir = util.root_pattern('.texlabroot', 'texlabroot', '.git', '.latexmkrc', 'Tectonic.toml'),
  }
```
I would suggest to experiment a little bit and see what order works for yo
