### ISSUE TITLE
code_action source.organizeImports does not works even if LSP server supports it

### ISSUE THREAD

**Issue by RishabhRD** [neovim/nvim-lspconfig#350]
- `nvim --version`: NVIM v0.5.0-691-g542022aae
- nvim-lsp version(commit hash): 60133c47e0fd82556d7ca092546ebfa8d047466e

- What language server(If the problem is related to a specific language server): tried on jdtls and tsserver
- Operating system/version: archlinux
- Terminal name/version: st
- `$TERM`: st-256color

### How to reproduce the problem from neovim startup

```
open a java project in neovim
open a java file
in command mode enter: lua vim.lsp.buf.code_action({ source = { organizeImports = true } })
```

### Actual behaviour
After calling code_action with organizeImports=true as lua vim.lsp.buf.code_action({ source = { organizeImports = true } }), throws
the following error:

Error executing vim.schedule lua callback: ...onfig/nvim/plugged/nvim-lspconfig/lua/nvim_lsp/jdtls.lua:109: bad argument #1 to 'ipairs' (table expected, got nil)

### Expected behaviour

A nice quickfix window containing all possible imports if necessary.

**Comment by mjlbach** [comment]
I'm closing this, since this isn't implemented with standard code-actions. [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) is the best option for this, as it handles all of the weird, non-spec compliant [handlers](https://github.com/mfussenegger/nvim-jdtls/blob/da0d007798e24b744f0500148b7d5cb003b10c2a/lua/jdtls.lua#L251-L261).
