### ISSUE TITLE
attempt to index local 'lsp' (a nil value)

### ISSUE THREAD

**Issue by jbaek7023** [neovim/nvim-lspconfig#364]
Error message:
```
Error detected while processing /Users/jbaek/.vim/plugged/nvim-lspconfig/plugin/nvim_lsp.vim:
line   14:
E5105: Error while calling lua chunk: .../jbaek/.vim/plugged/nvim-lspconfig/lua/nvim_lsp/util.lua:11: attempt to index local 'lsp' (a nil value)
```

I'm not sure why it's failing... Is it because my nvim is 0.4.4??
I ran `brew install --HEAD neovim` but 0.4.4 is still the latest. 

- `nvim --version`: NVIM v0.4.4
- nvim-lsp version(commit hash):
- `:checkhealth` result
- What language server(If the problem is related to a specific language server):
- Operating system/version:
- Terminal name/version:
- `$TERM`:

**Comment by jbaek7023** [comment]
upgraded vim to 0.5 and it worked

**Comment by tommyalatalo** [comment]
> upgraded vim to 0.5 and it worked

So you went to a nightly build of nvim to fix this or what? nvim is still only released as 0.4.4 on stable branch as far as I can tell.

**Comment by adamhooper** [comment]
This error still happens on the latest stable release of neovim, v0.4.4.

Could a maintainer please reopen this issue, and then close it when v0.5.x is released? That way, affected users could subscribe and be notified when the issue is resolved.

**Comment by mjlbach** [comment]
> This error still happens on the latest stable release of neovim, v0.4.4.

That's because LSP support is a feature of 0.5? It's in the first couple lines of the readme. 

![image](https://user-images.githubusercontent.com/13316262/112865128-53669980-906d-11eb-9c4f-ced89c544a7e.png)

I'm not going to pin the issue, as if people aren't reading the readme, we have bigger problems.

**Comment by adamhooper** [comment]
> That's because LSP support is a feature of 0.5? It's in the first couple lines of the readme.

> I'm not going to pin the issue, as if people aren't reading the readme, we have bigger problems.

Evidently, people aren't reading the readme. Four issues (this, #65, #81, #436 -- some from 2019) all came from this same problem.

I'm willing to bet we're all smart people :). I can't speak for the others; but personally, I skimmed past that part of the README because in my head, these facts came first:

* This project has 1.6k stars. That never happens for a plug-in on a pre-release piece of software
* This project is in the `neovim` organization. It's rare for an "official" plug-in to not work on any "official" release for so long.
* I've never encountered a vim plugin with this restriction. (I don't tend to read the install instructions of vim plugins, PyPI modules, npm libraries, Maven libraries, etc.)

The project is a victim of its own success, it seems.

Anyway. I don't want to cramp your style -- you're doing lots of awesome work! Just know that some of us on the sidelines would love a way to know when we can take advantage of what I imagine is an awesome vim plugin :).

**Comment by 71GA** [comment]
I had similar problem and the problem was the version of `nodejs` which should be higher or equal to 14... Practically useless as it is impossible to install this one on any kind of stable Linux.
