### ISSUE TITLE
setup() on_attach signature

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim-lspconfig#63]
doc for `setup()` mentions:

> {on_attach}
>    `function(client)` executed with the current buffer as the one the {client}      is being attached-to. This is different from   |vim.lsp.start_client()|'s on_attach parameter, which passes the {bufnr} as the second parameter instead. Useful for doing buffer-local setup.

The fact that the doc feels the need to mention "This is different from ..." is a strong hint that it shouldn't be different. One or the other should be changed.

**Comment by norcalli** [comment]
That is the intention, but it was only made apparent once I started implementing custom commands and I realized that there's no way to create commands for a target buffer, only the current buffer. That's the only time I thought that the `on_attach` in master was insufficient. That's why I am prototyping this version. It's one of the things that I thought I would merge into master. That and the settings stuff.
