### ISSUE TITLE
Pyright configuration for disabling hint diagnostics

### ISSUE THREAD

**Issue by horta** [neovim/nvim-lspconfig#726]
According to: https://github.com/microsoft/pyright/issues/982#issuecomment-683913182

> Pyright never emits an error or warning for unused "self". It does emit a "hint" diagnostic that clients can either ignore or use to display the unreferenced variable in gray if they choose. VS Code handles this fine, but some clients (editors) may not properly handle this hint and display it as a warning instead. Which client are you using?

AFAIK, there is not way to currently disable it using nvim-lspconfig:

```
require'lspconfig'.pyright.setup{}

  Commands:
  
  Default Values:
    cmd = { "pyright-langserver", "--stdio" }
    filetypes = { "python" }
    root_dir = <function 1>
    settings = {
      python = {
        analysis = {
          autoSearchPaths = true,
          useLibraryCodeForTypes = true
        }
      }
    }
```

Here is the diagnostic I would like to suppress:

<img width="773" alt="Screenshot 2021-02-10 at 12 08 42" src="https://user-images.githubusercontent.com/514522/107508325-be7d0f00-6b98-11eb-94c4-57fbe47d2328.png">

**Comment by mjlbach** [comment]
You can pass any settings to pyright that you would with any other client, just override the `settings` key that you pass into pyright. The issue is pyright's language server (I believe) doesn't allow you to selectively disable returning hints per diagnostic type like you want. 

If you want to disable showing hints (generally), you'll need to override the diagnostic handler in neovim to pass a severity limit for virtual text. If you want to only disable one type of hint, I guess you could write a filtering function to filter out diagnostics of the type you are seeing (both of which, are no implemented/associated with nvim-lspconfig, which only handles starting your language server).

**Comment by imsofi** [comment]
@horta Did you ever find out a way to do this? I am so close to giving up on the LSP-ecosystem in neovim because it keeps telling me im using `self` "wrong".

**Comment by mjlbach** [comment]
In that example why would you not make it a static method?

**Comment by mjlbach** [comment]
You have access to the diagnostic list in on_publish_diagnostics, see here for an example of how it's sorted (you could apply a filter as well) https://github.com/neovim/neovim/blob/d2be261e8d1bcf165346255ae701564a5f62bf7d/runtime/lua/vim/lsp/diagnostic.lua#L1008-L1013

You'd want to make a custom version of that function, and then override the handler to call that. https://github.com/neovim/neovim/blob/d2be261e8d1bcf165346255ae701564a5f62bf7d/runtime/lua/vim/lsp/diagnostic.lua#L967-L983

**Comment by mjlbach** [comment]
Anyways, this isn't neovim's fault, pyright may or may not have some configuration option you can pass to it, we literally just pipe the diagnostics directly from pyright.

**Comment by disrupted** [comment]
@imsofi update pyright to the latest version. This behaviour has been fixed for a while now.

**Comment by disrupted** [comment]
Here's the related (closed) issue for more information: https://github.com/microsoft/pylance-release/issues/194

**Comment by horta** [comment]
> @horta Did you ever find out a way to do this? I am so close to giving up on the LSP-ecosystem in neovim because it keeps telling me im using `self` "wrong".

I don't remember but

```
@property
def sequence(_):
    ...
```

might do the trick...

**Comment by MarcelRobitaille** [comment]
For anyone coming back to this, I am using the following based on @mjlbach's suggestions:

```lua
function filter(arr, func)
	-- Filter in place
	-- https://stackoverflow.com/questions/49709998/how-to-filter-a-lua-array-inplace
	local new_index = 1
	local size_orig = #arr
	for old_index, v in ipairs(arr) do
		if func(v, old_index) then
			arr[new_index] = v
			new_index = new_index + 1
		end
	end
	for i = new_index, size_orig do arr[i] = nil end
end


function filter_diagnostics(diagnostic)
	-- Only filter out Pyright stuff for now
	if diagnostic.source ~= "Pyright" then
		return true
	end

	-- Allow kwargs to be unused, sometimes you want many functions to take the
	-- same arguments but you don't use all the arguments in all the functions,
	-- so kwargs is used to suck up all the extras
	if diagnostic.message == '"kwargs" is not accessed' then
		return false
	end

	-- Allow variables starting with an underscore
	if string.match(diagnostic.message, '"_.+" is not accessed') then
		return false
	end

	return true
end

function custom_on_publish_diagnostics(a, params, client_id, c, config)
	filter(params.diagnostics, filter_diagnostics)
	vim.lsp.diagnostic.on_publish_diagnostics(a, params, client_id, c, config)
end

vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
	custom_on_publish_diagnostics, {})
```

**Comment by Swoogan** [comment]
There is a much easier way to disable these hints. Pyright sends these hints to neovim because neovim is specifically asking for them (and probably shouldn't be -- [see this discussion](https://github.com/microsoft/pyright/issues/4652) and [this comment](https://github.com/microsoft/pyright/issues/982#issuecomment-684013085)).
You can configure neovim to not ask for them:
```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.publishDiagnostics.tagSupport.valueSet = { 2 } 
require('lspconfig')['pyright'].setup{
    capabilities = capabilities,
    on_attach = on_attach
}
```
For reference, [here are the tags](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag).

**Comment by MarcelRobitaille** [comment]
@Swoogan I prefer my method. It's more customizable. I can choose exactly what diagnostics I want to ignore. For example, `*args`, `**kwargs`, anything starting with `_`, etc.

**Comment by Swoogan** [comment]
@MarcelRobitaille It certainly is more customizable. In my case I wanted all hints to be removed because I have them coming from other tools and was getting duplicate diagnostics. I wonder though, could it be implemented in the client's handler instead of globally? Then you wouldn't need to check the source. For example:
```
require('lspconfig')['pyright'].setup {
  on_attach = function(client, buffer)
    client.handlers["textDocument/publishDiagnostics"] = function(...) end
    on_attach(client, buffer)
  end,
```

**Comment by MarcelRobitaille** [comment]
@Swoogan I will try that, thanks!

**Comment by disrupted** [comment]
@Swoogan yes, that is possible.

**Comment by zhou13** [comment]
For anyone that is using LunarVim or `nlsp-settings.nvim` so that is is inconvenient to call `require('lspconfig')['pyright'].setup`, a solution is to use
```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.publishDiagnostics.tagSupport.valueSet = { 2 }
local util = require("lspconfig.util")
util.default_config = vim.tbl_extend("force", util.default_config, {
  capabilities = capabilities,
})
```

That said, I believe this is a bug since it is stated very clear [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag) that **Clients are allowed to render diagnostics with this tag faded out** when the tag is 1.

**Comment by tan-wei-xin-alez** [comment]
those using lazyvim can add the following to a file in .config/nvim/lua/plugins as mentioned [here](https://github.com/microsoft/pyright/discussions/5852#discussioncomment-6874502)
```
return {
  -- change nvim-lspconfig options
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      -- https://github.com/microsoft/pyright/discussions/5852#discussioncomment-6874502
      pyright = {
        capabilities = {
          textDocument = {
            publishDiagnostics = {
              tagSupport = {
                valueSet = { 2 },
              },
            },
          },
        },
      },
      ruff_lsp = {},
    },
  },
}
```
