### ISSUE TITLE
setting message_level has no effect after removing deprecated handlers

### ISSUE THREAD

**Issue by otijhuis** [neovim/nvim-lspconfig#745]
- `nvim --version`: v0.5.0-dev+1097-g18f90336c
- nvim-lsp version(commit hash): 1eb00d7c2ad2efadac85529eccc46f22986bf140
- What language server (If the problem is related to a specific language server): using elixirls but it's a general issue
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): yes
- Is the problem isolated to a particular language server: no
- Operating system/version: macOS Big Sur

### How to reproduce the problem from neovim startup

Use any language server config from lspconfig.
Set the message_level in the setup to warning or error.

### Actual behaviour

Info messages are still shown when 'window/showMessage' callback is called.

### Expected behaviour

Info messages shouldn't be shown if message_level is warning or error.

### Expected cause

Recently a PR was merged (#509) that removed deprecated handlers. The code that was removed also removed the message_level check. I also checked the handlers in the neovim code and the 'window/showMessage' handler does not check the message_level but the 'window/logMessage' handler does check the log_level. Looks like this needs to be added to neovim (or message_level should be removed from lspconfig docs/code if this was intentional).

**Comment by mjlbach** [comment]
This was semi-intentional but I realize now it was a bit of an oversight. 

@teto @tjdevries for things like this, having a namespace for lsp options would be useful. Otherwise, what we have to do is either 

A) Wrap handlers to add options (see [here](https://github.com/neovim/nvim-lspconfig/pull/509/files#diff-0e1bd346624fa540fa153e867fbc2036ced5c83d5cd7d79d9308df1328b7c879L38-L40))

B) Ask users to always wrap handlers in their own config, which is easy but there are probably some options (like this one) that should be supported

**Comment by otijhuis** [comment]
Personally I wouldn't mind doing the wrapping myself. It's really easy to do and it turned out that I needed to filter out specific messages anyway. Took only a few lines of code. Some messages are useful, some aren't. Filtering out all the info messages might not be that useful anyway. Removing message_level from the code and replacing it in the docs with a handler example would probably suffice. I don't know if there are other cases where another solution would be better.
