### ISSUE TITLE
Is it possible to disable lsp in node_modules directory file?

### ISSUE THREAD

**Issue by ecosse3** [neovim/nvim-lspconfig#867]
Hello,

I would like to disable LSP client or just efm langserver when I'm in the file which is inside node_modules directory.

Because of efm and prettier errors related to my config I can't read anything:
![image](https://user-images.githubusercontent.com/17691791/115966936-20121000-a530-11eb-8ba2-a6b480c08670.png)

Is it possible? I can provide my lsp/efm config if needed.
Maybe some particular vim BufEnter syntax to emit `:LspStop` inside node_modules dir file?

Thank you!

**Comment by mjlbach** [comment]
Usage questions belong on our discourse, you can find the link in the readme.

________________________________
From: Łukasz Kurpiewski ***@***.***>
Sent: Saturday, April 24, 2021 10:08:10 AM
To: neovim/nvim-lspconfig ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [neovim/nvim-lspconfig] Is it possible to disable lsp in node_modules directory file? (#867)


Hello,

I would like to disable LSP client or just efm langserver when I'm in the file which is inside node_modules directory.

Because of efm and prettier errors related to my config I can't read anything:
[image]<https://user-images.githubusercontent.com/17691791/115966936-20121000-a530-11eb-8ba2-a6b480c08670.png>

Is it possible? I can provide my lsp/efm config if needed.
Maybe some particular vim BufEnter syntax to emit :LspStop inside node_modules dir file?

Thank you!
