### ISSUE TITLE
Issues with pyright autocompletion 

### ISSUE THREAD

**Issue by Trid-collab** [neovim/nvim-lspconfig#933]
I am newbie to python programing and lua version of init.lua for nvim. I am using nvim nightly on WSL2 - Ubuntu 20.04
I normally try learning using simple "*.py" files kept in a folders in in my Win 10 side - which get mounted on WSL by /mnt/c/Users/XXX/python_tutorial/. I have installed pyright server using "kabouzeid/nvim-lspinstall" plugin in my init.lua 
Everything - autocomplete works well when I have .py file in WSL $HOME folder., but when I try to run nvim on .py file on my /mnt/c/Users/XXX/python_tutorial/  the auto complete doesn't work. This issue didn't happen when I used earlier init.vim with coc pyroght server install. 

After some reading through your Readme on you site I put an requirement.txt or setup.py on the win10 python folder and then the autocomplete seemed to work. Could this be set to work like the coc pyright server where this was not required . It would save a lot of hassles for a learner like me who might keep multiple py folders as per learning and not necessarily doing a project with setup.py or requirements.txt

**Comment by mjlbach** [comment]
The point is moot, we changed this a long time ago (you don't need a setup.py) https://github.com/neovim/nvim-lspconfig/blob/f68f7d4c30abb3e4b8ebe6e3a604cc6f9eb924e8/lua/lspconfig/pyright.lua#L30-L33

In defense of root directory markers.

1. You should always put your projects, even scratch projects, under version control and include a requirements.txt/pyproject.toml
2. Not using root directory markers like `setup.py` can cause severe headaches for servers that *require* root directory markers or *need* root directories to be correct in order to index your entire project
