### ISSUE TITLE
LSPs in Docker

### ISSUE THREAD

**Issue by danymat** [neovim/nvim-lspconfig#938]
Hello everyone, 

I'm using neovim at work, with my config files, but I cannot install third parties applications such as node. So I cannot create some lsp servers that I need to work. I thought about creating a docker-compose with all my lsp's.
Is it possible? 
If so, is there a documentation for me to process?

Sincerely, Daniel.

**Comment by lithammer** [comment]
Please refer to our Discourse (https://neovim.discourse.group) for usage questions and discussions!

However I think using docker-compose will be hard since the servers communicate via stdin/stdout and docker-compose messes with the output. You also need to do something like `--volume $HOME:$HOME` so that paths align for workspaces and root markers. Your best chance is probably using docker directly. Something like this:

```lua
require("lspconfig").yaml.setup({
  cmd = {
    "docker",
    "run",
    "--rm",
    "-it",
    "-v",
    vim.loop.os_homedir() .. ":" .. vim.loop.os_homedir(),
    "lspcontainers/yaml-language-server",
    "--stdio"
 }
})
```

**Comment by ApolloBian** [comment]
@lithammer I can verify that this idea works, the cmd need to change from `-it` to `-i`. I was working with a huge cpp project and the toolchain only works on certain debian distributions. In order to code on my Macbook, I setup a clangd LSP using the following settings:
```lua
require('lspconfig').clangd.setup {
    cmd = {
        "docker",
        "run",
        "-i",
        "--rm",
        "-v",
        vim.loop.os_homedir() .. ":" .. vim.loop.os_homedir(),
        "docker_img_that_contain_the_toolchain",
        "/abs_path_to_clangd/clangd",
        "--background-index",
        "--clang-tidy",
        "--clang-tidy-checks=performance-*,bugprone-*",
        "--all-scopes-completion",
        "--completion-style=detailed",
        "--header-insertion=iwyu",
        "--pch-storage=disk",
        "--compile-commands-dir=build64_release/",
    },
}
```

Works perfectly :-)
