### ISSUE TITLE
Adding a bit more documentation regarding how to install language servers

### ISSUE THREAD

**Issue by g96k** [neovim/nvim-lspconfig#988]
Would appreciate it if you can explain  what exactly the **cmd** and  **cmd is executable** expect and where do they expect it in order to start properly.

Adding screenshots from java and tsserver 

![image](https://user-images.githubusercontent.com/69681813/122476296-99792c80-cfce-11eb-8ff8-78e2f684b207.png)

![image](https://user-images.githubusercontent.com/69681813/122477362-42745700-cfd0-11eb-9c84-ce08f167e869.png)

**Comment by mjlbach** [comment]
This is documented in `vim.lsp.start_client()`

**Comment by g96k** [comment]
well the servers are for sure installed, then the question would be how to set the path correctly.

**Comment by mjlbach** [comment]
If this was installed via lspinstall, as your logs indicate, you'll have to get support via their issue tracker. I'm not familiar with the inner workings of how that plugin overrides cmd to point at its install location. Otherwise, you can ask on our discourse https://neovim.discourse.group/

**Comment by g96k** [comment]
I did ask there first, this is i've got as a response
kabouzeid commented 8 hours ago
This is not part of lspinstall but part of lspconfig :)

**Comment by mjlbach** [comment]
Right, so I can tell you 100% your issue is that your language server is not installed correctly. `LspInfo` will tell you that. This repository doesn't install/manage language servers for you.

If you want to install the language server *without* lspinstall, you can follow CONFIG.md [here](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) or, better yet, for java, you should probably be using [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) which includes installation instructions in the readme.

**Comment by lithammer** [comment]
To elaborate, `cmd` is an array of the form `{ bin, arg1, arg2, ..., argN }`. Where `bin` is either an absolute path or just the name of the binary if available in `$PATH`. So for `tsserver` it would be something like this:

```lua
cmd = {"typescript-language-server", "--stdio"}
```

Or 

```lua
cmd = {"/usr/local/bin/typescript-language-server", "--stdio"}
```

**Comment by g96k** [comment]
i take it back it was actually the plugin's fault 

![image](https://user-images.githubusercontent.com/69681813/122533990-c6f3c380-d02a-11eb-8aad-da821bc4026f.png)

now java should be a bit harder than an npm install :D
